# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: auto  # Use coverage of base commit as target
        threshold: 2%  # Allow 2% drop without failing
        informational: false  # Fail PR if coverage drops significantly

    patch:
      default:
        target: 80%  # New code should have 80% coverage
        informational: true  # Don't fail, just report

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true  # Only comment if coverage changes

ignore:
  - "tests/**/*"
  - "**/__pycache__/**"
  - "**/conftest.py"

